### ISSUE TITLE
iOS Xamarin Support

### ISSUE THREAD

**Issue by DavePilks** [pgstath/Sharp.Xmpp#4]
Has this ever been tested with iOS?

**Comment by pgstath** [comment]
Well no this is not tested with iOS. However, I have run some compatibility tests from Xamarin and I remember that only a few items would need modification. 
However, my biggest concern with iOS would be  XMPP support in general, iOS does not allow persistent TCP connections, on the background, afaik, and XMPP and especially this library do need them, in order to have a background active connection.
