### ISSUE TITLE
group chat functionality

### ISSUE THREAD

**Issue by yon86** [pgstath/Sharp.Xmpp#5]
how can one build group chat functionality? thanks

**Comment by pgstath** [comment]
You can see https://github.com/pgstath/Sharp.Xmpp/issues/1. One should implement http://xmpp.org/extensions/xep-0045.html, which is not one of the simplest XMPP specs. I could guide you through Sharp.Xmpp "internals" and how you can start writing an extension, but it will require some effort in order to develop a fully compliant solution.
