### ISSUE TITLE
XML Stream Issue

### ISSUE THREAD

**Issue by DavePilks** [pgstath/Sharp.Xmpp#8]
Hi

I am trying to use the branch where we can define the host address in teh constructor for the XMPPClient (dev-rafaneri).

I can create the client but I get the following error when I try to call the Connect() method.

"The XML stream could not be negotiated."

When I drill down, I get to the folllwoing inner exception

{"'', hexadecimal value 0x15, is an invalid character. Line 1, position 1."}

I am assuming that when Sharp.XMPP tries to deserialise the stream, it is expecting a different encoding.

Do you have any idea why this is occuring and/or how to fix it?

I can connect to the server via the Matrix SDK.

**Comment by pgstath** [comment]
Hi,
I have not encountered something like this, but it might be possible, or it might be related to the process of negotiating the encryption. 
What kind of server do you use? It would be extremely helpful if you had access to the server's log and post the relevant XML stanza. You are going to need this in order to do some more advanced debugging.
Also from what point in code is the exception raised?

**Comment by chintanrn** [comment]
Hi DavePilks,

Kindly let me know if you found the solution. I am facing same problem.

Thanks and Regards,
CNaik.

**Comment by elveejay1** [comment]
I also have this problem - is there a solution?
